### ISSUE TITLE
Create a Template for Pull Request

### ISSUE THREAD

**Issue by tb-rules10** [Robotics-Club-BMU/CV-Zone#10]
Check this link for some help : https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by tb-rules10** [comment]
Can you assign this issue to me?

**Comment by MohithReddy1** [comment]
Can you comment your name and explain what you want do.

**Comment by tb-rules10** [comment]
Hey i'm Tanishq i want to create a pull request template for this repo.

**Comment by tb-rules10** [comment]
Can i create some issue templates as well?
