### ISSUE TITLE
Capturing an Image

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#100]
Write a code for Capturing an Image using OpenCV.

Once you are over with that create your folder(Capturing an Image) in the Basics_of_OpenCV folder update your code, add output images and create a readme file and add details in the readme file.

folder format: CV-Zone -> Basics_of_OpenCV -> create your folder(Capturing an Image) -> files

**Comment by tb-rules10** [comment]
Assign this to me.
