### ISSUE TITLE
Real-Time Text Detection 

### ISSUE THREAD

**Issue by tb-rules10** [Robotics-Club-BMU/CV-Zone#108]
Make a project for Real-Time Text Detection using open cv.

folder format: CV-Zone -> Projects -> create your folder(Text Detection) -> files

**Comment by tb-rules10** [comment]
I would like to work on this.

**Comment by tb-rules10** [comment]
Can i make different projects for live text detection & text detection from image?

**Comment by MohithReddy1** [comment]
you can
