### ISSUE TITLE
Facial Landmarks Detection

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#109]
Do project on Facial Landmarks Detection using OpenCV.

Once you are over with that create your own folder(Facial Landmarks Detection) in Projects folder update your codes, add input and output images and create readme file and add details in readme file.

**folder format: CV-Zone -> Projects -> create your folder(Facial Landmarks Detection) -> files**

**Comment by tb-rules10** [comment]
Assign me this
