### ISSUE TITLE
Automatic_Number_Plate_Recognition

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#110]
Do project on Automatic Number Plate Recognition using OpenCV.

Once you are over with that create your own folder(Number Plate Recognition) in Projects folder update your codes, add Input and output video(or screen recording) and create readme file and add details in readme file.

**folder format: CV-Zone -> Projects -> create your folder(Number Plate Recognition) -> files**

**Comment by tb-rules10** [comment]
I'd like to try this one.
