### ISSUE TITLE
Cartooning an Image

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#111]
Write a code to Cartooning an Image using OpenCV.

Once you are over with that create your own folder (Cartooning an Images) in Image_Manipulations folder update your code, add Input and output images and create readme file and add details in readme file.

**folder format: CV-Zone -> Image_Manipulations -> create your folder(Cartooning an Image) -> files**

**Comment by tb-rules10** [comment]
I'd like to try this one.
