### ISSUE TITLE
Sharpening an image - Image_Manipulations

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#20]
Write a code for Sharpening an image using OpenCV.

Once you are over with that create your own folder(Sharpening an image) in Image_Manipulations folder update your code, add input and output Images and create readme file and add details in readme file.

**Comment by charan1906** [comment]
I would like to work on the issue, can you please assign this to me?

**Comment by kriti-banka** [comment]
I would like to work on this. Please assign me this

**Comment by MohithReddy1** [comment]
This issue is already assigned to @charan1906.
