### ISSUE TITLE
Reading-Writing-and-displaying-images

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#3]
Write a code for Reading-Writing-and-displaying-images using OpenCV.

Once you are over with that create your own folder in Basics_of_OpenCV folder update your code, add input and output Images and create readme file and add details in readme file.

**Comment by anmolj7** [comment]
Hey, I'm interested on working on this, could you assign me this issue.

**Comment by MohithReddy1** [comment]
I have seen your code. It was nice. And add writing image code(for example resized write image in folder) in your code
