### ISSUE TITLE
Blob Detection

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#34]
Write a code for Blob Detection using OpenCV.

Once you are over with that create your own folder(Blob Detection) in Image_Segmentation folder update your code, add input and output Images and create readme file and add details in readme file.

**Input Image**

![image](https://user-images.githubusercontent.com/65151565/137736089-e9e17c64-d584-4c4b-b929-0da01f050324.png)

**Comment by tb-rules10** [comment]
Assign this to me
