### ISSUE TITLE
Grayscaling an Image

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#4]
Grayscaling is process by which an image is converted from a full color to shades of grey (black & white).

Write a code for Grayscaling an image using OpenCV.

Once you are over with that create your own folder in Basics_of_OpenCV folder update your code, add input and output Images and create readme file and add details in readme file.

**Comment by anmolj7** [comment]
Hey I'm interested in working on this project, could you assign me this issue!

**Comment by anmolj7** [comment]
is this fine?
