### ISSUE TITLE
Live Sketch Using Webcam

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#44]
Write a code for Live Sketch Using Webcam using OpenCV.

Once you are over with that create your own folder(Live Sketch Using Webcam) in Image_Manipulations folder update your code, add original and Live sketch images and create readme file and add details in readme file.

**Comment by tb-rules10** [comment]
Assign this to me

**Comment by tb-rules10** [comment]
Unassign me from this as i have checked the code but i'm still unable to draw a line.
I'm i thinking that the pblm might be my laptop as it has a vga cam.
PR #48
