### ISSUE TITLE
Image Resizing

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#54]
Write a code for Resizing images using OpenCV.

Once you are over with that create your own folder(Image Resizing) in Basics_of_OpenCV folder update your code, add input and output images and create readme file and add details in readme file.

folder format: CV-Zone -> Basics_of_OpenCV -> create your folder(Image Resizing) -> files

**Comment by ayushsaini12** [comment]
i can do this

**Comment by MohithReddy1** [comment]
@tb-rules10 You have already 3 active issues assignees. Limit is 3 issues. If you done with this then I will assignees other. So I am assigning this to @ayushsaini12.
