### ISSUE TITLE
Document-Scanner

### ISSUE THREAD

**Issue by MohithReddy1** [Robotics-Club-BMU/CV-Zone#56]
Do project on Document-Scanner using OpenCV.

Once you are over with that create your own folder(Document-Scanner) in Projects folder update your codes, add Input and output and create readme file and add details in readme file.

folder format: CV-Zone -> Projects -> create your folder(Document-Scanner) -> files

**Comment by tb-rules10** [comment]
Does it mean that we have to scan the document using our laptop's webcam?

**Comment by MohithReddy1** [comment]
Input the image(clicked with phone)

Once check this reference 
![image](https://user-images.githubusercontent.com/65151565/138023851-d0232b00-c54a-4b62-b3ce-ef91dc94d31c.png)
